settings:
  time: "10"
  nbOfQuestions: "5"
  textToBeStarted: "The game hasn't started yet, press START to begin! You can also just chat ;)"
  textEnded: "Press START to begin a new round."
  
quizDb:
  host: "ec2-54-75-248-49.eu-west-1.compute.amazonaws.com"
  port: "5432"
  user: "fagrivvjyjzmri"
  password: "fcde70bfa16390ab4b99912d798748a34fa5d31de9a5110588fe0750eaac5eb6"
  database: "d24kgrc4bsq3v8"